# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d17128c2bf91bd61e6b48b585ba08b50130f7289c3b6164b657cbcf18129378d05a0fb62d5a9f5c4fa46ea863f61e996225f584772daa7ef81f83a5229cec99

test:
  secret_key_base: dc32bef653e7049a250b6c41ae261e3e13c456a8c1e4f5b1c31a46c580186e45df27fd0278d91e65105610f9022ebca0e163981fe4f94907763bb20d93208418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
